{% set name = "interegular" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/interegular-{{ version }}.tar.gz
  sha256: ea4645abace93d9f39d341205686a60b79777a43d94400933effb9c8f2901825

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - interegular
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MegaIng/regex_intersections
  summary: a regex intersection checker
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pavelzw
