{% set name = "interegular" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/interegular-{{ version }}.tar.gz
  sha256: d9b697b21b34884711399ba0f0376914b81899ce670032486d0d048344a76600

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - interegular
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MegaIng/regex_intersections
  summary: a regex intersection checker
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pavelzw
